all:
	./compile.sh
	./compile.sh

.PHONY: clean

clean:
	@echo Cleaning files...
	@rm -f gdd_dsw_icg.aux gdd_dsw_icg.idx gdd_dsw_icg.lof gdd_dsw_icg.toc gdd_dsw_icg.log gdd_dsw_icg.lot setup.log

hardclean:
	@echo Cleaning files...
	@rm -f gdd_dsw_icg.aux gdd_dsw_icg.idx gdd_dsw_icg.lof gdd_dsw_icg.toc gdd_dsw_icg.log gdd_dsw_icg.lot setup.log
	@echo Deleting PDF.
	@rm -rf gdd_dsw_icg.pdf
